"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
declare global{interface Window{L:any}}
type P=[number,number];type K="uv"|"wind"|"fog"|"crowd"|"facility"|"shade"|"temp";
const tools:[K,string,string][]=[["uv","☀","자외선"],["wind","≋","해풍·빌딩풍"],["fog","〰","해무"],["crowd","♟","밀집도"],["facility","⌂","시설물"],["shade","▧","건물 그늘"],["temp","♨","온도"]];
const known:Record<string,P>={미포항:[35.1595,129.1707],청사포다릿돌전망대:[35.1607,129.1907],해운대역:[35.1631,129.1588],달맞이길:[35.1642,129.1788]};
export default function DynamicMap(){const node=useRef<HTMLDivElement>(null),map=useRef<any>(),path=useRef<any>(),marks=useRef<any[]>([]),env=useRef<any[]>([]);const[start,setStart]=useState("미포항"),[end,setEnd]=useState("청사포 다릿돌전망대"),[route,setRoute]=useState<P[]>([[35.1595,129.1707],[35.1607,129.1907]]),[active,setActive]=useState<K[]>(["wind","shade"]),[hour,setHour]=useState(14),[panel,setPanel]=useState(true),[status,setStatus]=useState("장소를 입력하고 경로 찾기를 누르세요."),[loading,setLoading]=useState(false);const uv=Math.max(0,8-Math.abs(hour-13)*2),temp=Math.round(23+7*Math.sin((hour-7)/24*Math.PI*2)),fog=Math.max(12,Math.round(72-3*hour+18*Math.cos(hour/3))),crowd=hour>=17&&hour<=21?76:hour>=11&&hour<=16?55:28;const samples=useMemo(()=>route.filter((_,i)=>i%Math.max(1,Math.floor(route.length/8))===0).slice(0,8),[route]);
useEffect(()=>{const init=()=>{const L=window.L;if(!L||!node.current)return;map.current=L.map(node.current).setView([35.16,129.18],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map.current)};if(window.L)init();else{const c=document.createElement("link");c.rel="stylesheet";c.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(c);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=init;document.head.appendChild(s)}},[]);
useEffect(()=>{if(!map.current)return;if(path.current)path.current.remove();path.current=window.L.polyline(route,{color:"#00a4c4",weight:9,opacity:.95}).addTo(map.current)},[route]);
useEffect(()=>{env.current.forEach(x=>x.remove());env.current=[];if(!map.current)return;const L=window.L,add=(x:any)=>env.current.push(x.addTo(map.current)),rad=((hour/24)*360-90)*Math.PI/180;active.forEach(k=>samples.forEach((p,i)=>{const q:[number,number]=[p[0]+((i%3)-1)*.001,p[1]+((i%2)-.5)*.0015];if(k==="shade"){const n=Math.sin(rad)*(.0005+Math.abs(hour-12)*.00012),e=-Math.cos(rad)*(.0005+Math.abs(hour-12)*.00012);add(L.polygon([[q[0]-.00025,q[1]-.0002],[q[0]+.00025,q[1]+.0002],[q[0]+n+.00025,q[1]+e+.0002],[q[0]+n-.00025,q[1]+e-.0002]],{color:"#42208e",fillColor:"#7148d7",fillOpacity:.48,weight:2}))}if(k==="fog")add(L.circle(q,{radius:130,color:"#087f9d",fillColor:"#9de3ec",fillOpacity:fog/130+.18,weight:3,dashArray:"10 6"}));if(k==="wind"){const sea=2.1+hour*.13,bld=4.3+(i%3)+hour*.08,w=(cls:string,dir:number,sp:number,dur:number)=>`<div class="windMotion ${cls}" style="--dir:${dir}deg;--dur:${dur}s"><span>≋</span><span>≋</span><span>≋</span><small>${sp.toFixed(1)}m/s</small></div>`;add(L.marker([q[0]+.0005,q[1]-.0005],{icon:L.divIcon({className:"windAnchor",html:w("seaFlow",(110+hour*13)%360,sea,Math.max(.45,1.8-sea*.15))})}));add(L.marker([q[0]-.0005,q[1]+.0005],{icon:L.divIcon({className:"windAnchor",html:w("buildingFlow",(35+hour*17+i*19)%360,bld,Math.max(.28,1.6-bld*.14))})}))}if(k==="uv")add(L.circle(q,{radius:100,color:"#e37d00",fillColor:"#ffd438",fillOpacity:uv/20+.12,weight:3}));if(k==="crowd")add(L.marker(q,{icon:L.divIcon({className:"crowdMark",html:`♟<b style="font-size:${18+crowd/5+i}px">♟</b>`})}));if(k==="facility"&&i%2===0)add(L.marker(q,{icon:L.divIcon({className:"facilityMark",html:["WC","쉼","편","P"][i%4]})}));if(k==="temp")add(L.marker(q,{icon:L.divIcon({className:"tempMark",html:`${temp+(i%3)-1}°`})}))}))},[active,hour,samples,fog,crowd,temp,uv]);
async function locate(name:string):Promise<P|null>{const key=name.replaceAll(" ","");if(known[key])return known[key];const a=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=kr&q=${encodeURIComponent(name+", 부산")}`).then(r=>r.json());return a[0]?[+a[0].lat,+a[0].lon]:null}
async function search(e:FormEvent){e.preventDefault();if(!start.trim()||!end.trim())return setStatus("두 장소를 모두 입력해 주세요.");if(/바다|해상|동해/.test(end))return setStatus("도착지는 육지 장소로 입력해 주세요.");setLoading(true);setStatus("입력한 장소의 보행 경로를 계산 중입니다…");try{const[a,b]=await Promise.all([locate(start),locate(end)]);if(!a||!b)throw Error("장소를 찾지 못했습니다.");let pts:P[]=[];try{const r=await fetch(`https://routing.openstreetmap.de/routed-foot/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`).then(x=>x.json());if(r.routes?.[0])pts=r.routes[0].geometry.coordinates.map((x:number[]):P=>[x[1],x[0]])}catch{}if(!pts.length)pts=Array.from({length:13},(_,i):P=>[a[0]+(b[0]-a[0])*i/12,a[1]+(b[1]-a[1])*i/12]);setRoute(pts);marks.current.forEach(x=>x.remove());const L=window.L;marks.current=[L.marker(a).addTo(map.current).bindPopup(`출발: ${start}`),L.marker(b).addTo(map.current).bindPopup(`도착: ${end}`)];map.current.fitBounds(L.latLngBounds(pts),{padding:[60,60]});setStatus(`${start} → ${end} 경로로 변경했습니다.`)}catch(err){setStatus(`${err instanceof Error?err.message:"경로 계산 실패"} 장소명을 더 구체적으로 입력해 주세요.`)}finally{setLoading(false)}}
const toggle=(x:K)=>setActive(active.includes(x)?active.filter(v=>v!==x):[...active,x]);return <main><header><b>〰 바닷길</b><span>입력 장소 기반 경로</span></header><div ref={node} id="map"/><section className="controls"><form className="inputs" onSubmit={search}><input value={start} onChange={e=>setStart(e.target.value)} placeholder="출발지"/><b>→</b><input value={end} onChange={e=>setEnd(e.target.value)} placeholder="도착지"/><button disabled={loading}>{loading?"계산 중…":"경로 찾기"}</button></form><div className="buttons">{tools.map(([k,i,n])=><button key={k} className={active.includes(k)?"on":""} onClick={()=>toggle(k)}><i>{i}</i>{n}</button>)}</div><p className="routeStatus">{status}</p></section>{panel?<aside><button className="panelClose" onClick={()=>setPanel(false)}>×</button><b>시간대별 예측</b><input type="range" min="0" max="23" value={hour} onChange={e=>setHour(+e.target.value)}/><strong>{String(hour).padStart(2,"0")}:00</strong><span>태양 고도 {hour>=6&&hour<=19?Math.max(4,63-Math.abs(hour-12)*9):0}°</span><div className="metrics"><p><i className="yellow"/>UV {uv}</p><p><i className="blue"/>해풍 {(2.1+hour*.13).toFixed(1)}</p><p><i className="orange"/>빌딩풍 {(4.3+hour*.08).toFixed(1)}</p><p><i className="cyan"/>해무 {fog}%</p><p><i className="pink"/>밀집도 {crowd}%</p><p><i className="red"/>온도 {temp}°</p></div></aside>:<button className="panelOpen" onClick={()=>setPanel(true)}>시간대별 예측 열기</button>}<div className="routeInfo"><b>입력 기반 AI 경로</b><span>입력 장소가 바뀔 때마다 경로와 환경 레이어가 함께 갱신됩니다.</span></div></main>}
