"use client";
import{useEffect,useRef,useState}from"react";
declare global{interface Window{L:any}}
type Kind="shade"|"fog"|"wind";const route:[[number,number],[number,number],[number,number],[number,number]]=[[35.1595,129.1707],[35.1607,129.176],[35.1604,129.183],[35.1607,129.1907]];
export default function MapApp(){const el=useRef<HTMLDivElement>(null),map=useRef<any>(),items=useRef<any[]>([]);const[active,setActive]=useState<Kind[]>(["shade","wind"]),[hour,setHour]=useState(14);
useEffect(()=>{const init=()=>{const L=window.L;if(!L||!el.current)return;map.current=L.map(el.current).setView([35.160,129.180],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map.current);L.polyline(route,{color:"#00a4c4",weight:9}).addTo(map.current)};if(window.L)init();else{const c=document.createElement("link");c.rel="stylesheet";c.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(c);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=init;document.head.appendChild(s)}},[]);
useEffect(()=>{items.current.forEach(x=>x.remove());items.current=[];if(!map.current)return;const L=window.L,add=(x:any)=>items.current.push(x.addTo(map.current));const sunAzimuth=(hour-6)*15-90,sun=sunAzimuth*Math.PI/180,shadowLength=(1.15+Math.abs(hour-12)*.3)*.001;const fogAzimuth=(hour<10?35:hour<16?70:110)*Math.PI/180,fogLength=(hour<9?2.3:hour<12?1.7:hour<17?.9:1.8)*.001;
if(active.includes("shade"))route.slice(0,3).forEach((p,i)=>{const north=Math.sin(sun)*shadowLength,east=-Math.cos(sun)*shadowLength;add(L.polygon([[p[0]-.00035,p[1]-.00028],[p[0]+.00035,p[1]+.00028],[p[0]+north+.00035,p[1]+east+.00028],[p[0]+north-.00035,p[1]+east-.00028]],{color:"#3d218c",fillColor:"#6e4bd3",fillOpacity:.52,weight:4,dashArray:"8 4"}))});
if(active.includes("fog"))route.slice(0,3).forEach((p,i)=>{const north=Math.sin(fogAzimuth)*fogLength,east=Math.cos(fogAzimuth)*fogLength;const width=.0007+i*.00015;add(L.polygon([[p[0]-width,p[1]-width],[p[0]+width,p[1]+width],[p[0]+north+width,p[1]+east+width],[p[0]+north-width,p[1]+east-width]],{color:"#087f9d",fillColor:"#9de3ec",fillOpacity:hour<10?.66:.42,weight:4,dashArray:"12 6"}))});
if(active.includes("wind"))route.forEach((p,i)=>{add(L.marker([p[0]+.0012,p[1]-.001],{icon:L.divIcon({className:"seaWind",html:"➜<b>해풍</b><small>4.2m/s</small>"})}));add(L.marker([p[0]-.0012,p[1]+.001],{icon:L.divIcon({className:"buildingWind",html:"➜<b>빌딩풍</b><small>6.1m/s</small>"})}))})},[active,hour]);
const toggle=(x:Kind)=>setActive(active.includes(x)?active.filter(v=>v!==x):[...active,x]);return <main><header><b>〰 바닷길</b><span>일출 05:31 · 일몰 19:17</span></header><div ref={el} id="map"/><section className="controls"><div className="inputs"><input defaultValue="미포항"/><b>→</b><input defaultValue="청사포 다릿돌전망대"/><button>AI 최적 경로</button></div><div className="buttons"><button className={active.includes("wind")?"on":""} onClick={()=>toggle("wind")}>➜ 해풍·빌딩풍</button><button className={active.includes("shade")?"on":""} onClick={()=>toggle("shade")}>▧ 건물 그늘</button><button className={active.includes("fog")?"on":""} onClick={()=>toggle("fog")}>〰 해무</button></div></section><aside><b>시간대별 환경 분석</b><input type="range" min="6" max="19" value={hour} onChange={e=>setHour(+e.target.value)}/><strong>{hour}:00</strong><span>태양 고도 {hour===12?63:Math.max(8,63-Math.abs(hour-12)*9)}°</span><div className="legend"><i className="purple"/>건물 그늘 <i className="cyan"/>해무<br/><i className="blue"/>해풍 <i className="orange"/>빌딩풍</div></aside><div className="info"><b>{active.includes("shade")?`${hour}시 그늘 방향 ${sunAzimuthLabel(hour)}`:"그늘 꺼짐"}</b><span>{active.includes("fog")?(hour<10?"오전 해무 넓음":"해무 영향 보통"):"해무 꺼짐"}</span><small>한글 설명은 지도 밖 패널에서 확인합니다.</small></div></main>}
function sunAzimuthLabel(h:number){return h<10?"북서쪽":h<14?"북쪽":h<17?"북동쪽":"동쪽"}
