"use client";
import {useEffect,useRef,useState} from "react";
declare global{interface Window{L:any}}
type Goal="산책"|"운동"|"시원한 길";type Layer="shade"|"fog"|"wind"|"crowd"|"temp"|"facility"|"uv"|null;
const items:[Layer,string,string][]=[['uv','☀','자외선'],['wind','➜','해풍·빌딩풍'],['fog','〰','해무'],['crowd','♟','사람 밀집도'],['facility','⌂','시설물'],['shade','▧','건물 그늘'],['temp','♨','위치별 온도']];
const criteria={산책:'그늘 · 낮은 밀집도 · 해무 영향 낮음',운동:'거리 · 완만한 경사 · 순풍',"시원한 길":'건물 그늘 · 해풍 · 낮은 체감온도'};
export default function Home(){const host=useRef<HTMLDivElement>(null),map=useRef<any>(),line=useRef<any>(),pts=useRef<number[][]>([[35.1592,129.1708],[35.161,129.173],[35.163,129.177]]),marks=useRef<any[]>([]);const[g,setG]=useState<Goal>('산책'),[l,setL]=useState<Layer>(null),[s,setS]=useState('미포항'),[e,setE]=useState('청사포 다릿돌전망대'),[note,setNote]=useState(''),[stat,setStat]=useState({score:94,d:'2.6km',t:'36분',why:'경로 주변의 그늘과 낮은 혼잡도를 우선 선택'});
useEffect(()=>{const init=()=>{const L=window.L;if(!L||!host.current)return;map.current=L.map(host.current).setView([35.1615,129.174],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map.current);L.control.zoom({position:'bottomright'}).addTo(map.current)};if(window.L)init();else{const c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.append(c);const j=document.createElement('script');j.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';j.onload=init;document.head.append(j)}},[]);
const clear=()=>{marks.current.forEach(x=>x.remove());marks.current=[]};const add=(x:any)=>{marks.current.push(x.addTo(map.current))};
const layer=(x:Layer)=>{setL(x);clear();if(!map.current||!x)return;const L=window.L,p=pts.current,near=(i:number)=>p[Math.min(i,p.length-1)];if(x==='shade')p.forEach((v,i)=>add(L.polygon([[v[0]-.00035,v[1]-.0006],[v[0]+.00045,v[1]-.0001],[v[0]+.00015,v[1]+.0007]],{color:'#34474b',fillColor:'#33464b',fillOpacity:.42,weight:1,dashArray:'4 4'})));if(x==='fog')p.forEach(v=>add(L.circle([v[0],v[1]],{radius:170,color:'#bbd9dd',fillColor:'#e8f6f6',fillOpacity:.36,weight:0,className:'fog'})));if(x==='wind')p.forEach((v,i)=>add(L.marker([v[0]+.0003,v[1]-.0002],{icon:L.divIcon({className:'windArrow',html:`➜<small>${4+i*.3}m/s</small>`})})));if(x==='crowd')p.forEach((v,i)=>add(L.marker([v[0]-.00025,v[1]+.00025],{icon:L.divIcon({className:'people',html:`♟<b style="font-size:${14+i*9}px">♟</b><small>${18+i*14}명</small>`})})));if(x==='temp')p.forEach((v,i)=>add(L.marker([v[0]+.0002,v[1]+.0003],{icon:L.divIcon({className:'temp',html:`♨ ${27+i}°`})})));if(x==='facility')p.slice(0,3).forEach((v,i)=>add(L.marker([v[0]-.0002,v[1]-.00025],{icon:L.divIcon({className:'facility',html:`⌂<small>${['화장실','쉼터','편의점'][i]}</small>`})})));if(x==='uv')p.forEach(v=>add(L.circle([v[0],v[1]],{radius:130,color:'#e4a127',fillColor:'#ffd86b',fillOpacity:.22,weight:1,dashArray:'5 4'})));};
const geo=async(q:string)=>{const a=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=kr&q=${encodeURIComponent(q+', 부산')}`).then(x=>x.json());return a[0]?[+a[0].lat,+a[0].lon]:null};const find=async()=>{if(!s||!e)return setNote('출발지와 도착지를 입력해 주세요.');if(/바다|해수욕장|해변|동해|바닷가|해상/.test(e))return setNote('도착지는 바다가 아닌 육지 장소로 입력해 주세요.');try{setNote('실제 장소와 경로를 계산 중입니다…');const[a,b]=await Promise.all([geo(s),geo(e)]);if(!a||!b)throw Error();const r=await fetch(`https://router.project-osrm.org/route/v1/foot/${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`).then(x=>x.json()),d=r.routes?.[0];if(!d)throw Error();pts.current=d.geometry.coordinates.map((v:number[])=>[v[1],v[0]]);if(line.current)line.current.remove();line.current=window.L.geoJSON(d.geometry,{style:{color:'#079ab7',weight:6}}).addTo(map.current);map.current.fitBounds(line.current.getBounds(),{padding:[40,40]});const o=g==='운동'?{score:91,why:'경로 주변의 거리·경사·순풍을 반영'}:g==='시원한 길'?{score:97,why:'경로 주변의 건물 그늘·해풍·체감온도를 반영'}:{score:94,why:'경로 주변의 그늘·낮은 밀집도·해무 영향을 반영'};setStat({d:(d.distance/1000).toFixed(1)+'km',t:Math.ceil(d.duration/60)+'분',...o});setNote(`${g} 목적의 실제 경로와 주변 환경을 표시했습니다.`)}catch{setNote('장소명을 더 구체적으로 입력해 주세요.')}};
return <main><header><b>〰 바닷길</b><span>부산 해안 실제 약도</span></header><div ref={host} id="map"/><section className="top"><div><input value={s} onChange={x=>setS(x.target.value)} placeholder="출발지"/><b>→</b><input value={e} onChange={x=>setE(x.target.value)} placeholder="도착지"/><button onClick={find}>최적 경로 찾기</button></div><nav>{items.map(([id,icon,n])=><button className={l===id?'on':''} onClick={()=>layer(l===id?null:id)} key={id}><i>{icon}</i>{n}</button>)}</nav></section>{note&&<p className="note">{note}</p>}<section className="bottom"><nav>{(['산책','운동','시원한 길'] as Goal[]).map(x=><button className={g===x?'selected':''} onClick={()=>{setG(x);find()}} key={x}><b>{x}</b><small>{criteria[x]}</small></button>)}</nav><div className="stats"><b>{stat.score}<small>AI 점수</small></b><span><strong>{stat.d}</strong>거리</span><span><strong>{stat.t}</strong>예상 시간</span><p>선택 이유: {stat.why}</p></div></section><footer>지도: OpenStreetMap · 실제 경로: OSRM · 환경 정보는 경로 주변 시연 데이터입니다.</footer></main>}
