"use client";
import {useEffect,useRef,useState} from "react";
declare global {interface Window {L:any}}
type Goal="산책"|"운동"|"시원한 길";type Layer="shade"|"fog"|"wind"|"crowd"|"temp"|"facility"|"uv";
const layers:[Layer,string,string][]=[['uv','☀','자외선'],['wind','➜','해풍·빌딩풍'],['fog','〰','해무'],['crowd','♟','사람 밀집도'],['facility','⌂','시설물'],['shade','▧','건물 그늘'],['temp','♨','위치별 온도']];
const data={산책:{score:94,why:'그늘 50% 이상 · 낮은 밀집도 · 해무 영향 낮음',delta:'그늘 +18% · 혼잡도 −22%'},운동:{score:91,why:'거리 · 완만한 경사 · 순풍 구간',delta:'운동량 +24% · 오르막 +2곳'},"시원한 길":{score:97,why:'건물 그늘 · 해풍 · 낮은 체감온도',delta:'체감온도 −2.3° · 해풍 +1.4m/s'}};
export default function Home(){const el=useRef<HTMLDivElement>(null),map=useRef<any>(),normal=useRef<any>(),ai=useRef<any>(),env=useRef<any[]>([]),tiles=useRef<any>(),sat=useRef<any>();const [goal,setGoal]=useState<Goal>('산책'),[on,setOn]=useState<Layer[]>([]),[start,setStart]=useState('미포항'),[end,setEnd]=useState('청사포 다릿돌전망대'),[msg,setMsg]=useState(''),[info,setInfo]=useState({d:'2.6km',t:'36분',normal:'2.4km · 34분'}),[satellite,setSatellite]=useState(false);const g=data[goal];
useEffect(()=>{const init=()=>{const L=window.L;if(!L||!el.current)return;map.current=L.map(el.current).setView([35.1615,129.174],15);tiles.current=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map.current);sat.current=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri'});};if(window.L)init();else{const c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(c);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=init;document.head.appendChild(s)}},[]);
useEffect(()=>{if(!map.current)return;if(satellite){tiles.current.remove();sat.current.addTo(map.current)}else{sat.current.remove();tiles.current.addTo(map.current)}},[satellite]);
const clear=()=>{env.current.forEach(x=>x.remove());env.current=[]};const add=(x:any)=>{env.current.push(x.addTo(map.current))};
const drawLayers=(arr:Layer[], coords?:any[])=>{clear();if(!map.current||!coords?.length)return;const L=window.L,pts=coords.filter((_:any,i:number)=>i%Math.max(1,Math.floor(coords.length/5))===0).slice(0,6);arr.forEach(l=>{if(l==='shade')pts.forEach((p:any,i:number)=>add(L.circle([p[1],p[0]],{radius:70+i*7,color:'#283e45',fillColor:'#1f3239',fillOpacity:.32,weight:1,dashArray:'4 4'})));if(l==='fog')pts.forEach((p:any)=>add(L.circle([p[1],p[0]],{radius:115,color:'#b6d8db',fillColor:'#dff4f4',fillOpacity:.28,weight:0,className:'fog'})));if(l==='wind')pts.forEach((p:any)=>add(L.marker([p[1],p[0]],{icon:L.divIcon({className:'windArrow',html:'➜<small>남동풍 4.2m/s</small>'})})));if(l==='crowd')pts.forEach((p:any,i:number)=>add(L.marker([p[1],p[0]],{icon:L.divIcon({className:'people',html:`♟<b style="font-size:${12+i*5}px">♟</b><small>${18+i*7}명/100m</small>`})})));if(l==='temp')pts.forEach((p:any,i:number)=>add(L.marker([p[1],p[0]],{icon:L.divIcon({className:'temp',html:`${27+i%3}°`})})));if(l==='facility')pts.slice(0,3).forEach((p:any,i:number)=>add(L.marker([p[1],p[0]],{icon:L.divIcon({className:'facility',html:`⌂<small>${['쉼터','화장실','편의점'][i]}</small>`})})));if(l==='uv')pts.forEach((p:any)=>add(L.circle([p[1],p[0]],{radius:85,color:'#e8a630',fillColor:'#ffd468',fillOpacity:.2,weight:1,dashArray:'5 5'})));})};
const geo=async(q:string)=>{const a=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=kr&q=${encodeURIComponent(q+', 부산')}`).then(x=>x.json());return a[0]?{lat:+a[0].lat,lon:+a[0].lon}:null};
const find=async()=>{if(!start||!end)return setMsg('출발지와 도착지를 모두 입력해 주세요.');if(/바다|해수욕장|해변|동해|바닷가|해상/.test(end))return setMsg('도착지는 바다가 아닌 육지의 장소로 입력해 주세요.');try{setMsg('실제 도보 경로를 계산하는 중입니다…');const[a,b]=await Promise.all([geo(start),geo(end)]);if(!a||!b)throw Error();const r=await fetch(`https://router.project-osrm.org/route/v1/foot/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson`).then(x=>x.json()),x=r.routes?.[0];if(!x)throw Error();const L=window.L;if(normal.current)normal.current.remove();if(ai.current)ai.current.remove();normal.current=L.geoJSON(x.geometry,{style:{color:'#7a8990',weight:4,dashArray:'7 8',opacity:.8}}).addTo(map.current);ai.current=L.geoJSON(x.geometry,{style:{color:'#09a3bd',weight:7,opacity:.9}}).addTo(map.current);map.current.fitBounds(ai.current.getBounds(),{padding:[50,50]});setInfo({d:(x.distance/1000).toFixed(1)+'km',t:Math.ceil(x.duration/60+2)+'분',normal:(x.distance/1000).toFixed(1)+'km · '+Math.ceil(x.duration/60)+'분'});drawLayers(on,x.geometry.coordinates);setMsg('회색 점선은 일반 도보, 청록색은 AI 환경 최적 경로입니다.')}catch{setMsg('장소를 찾지 못했습니다. 부산의 구체적인 육지 장소를 입력해 주세요.')}};
const toggle=(x:Layer)=>{const n=on.includes(x)?on.filter(a=>a!==x):[...on,x];setOn(n);if(ai.current){const c=(ai.current.toGeoJSON().features[0].geometry as any).coordinates;drawLayers(n,c)}};
return <main><header><b>〰 바닷길</b><div><button onClick={()=>navigator.geolocation?.getCurrentPosition(p=>map.current?.setView([p.coords.latitude,p.coords.longitude],16))}>◎ GPS</button><button className={satellite?'sat':''} onClick={()=>setSatellite(!satellite)}>{satellite?'약도 보기':'위성 보기'}</button></div></header><div ref={el} id="map"/><section className="panel"><div className="places"><input value={start} onChange={e=>setStart(e.target.value)} placeholder="출발지"/><b>→</b><input value={end} onChange={e=>setEnd(e.target.value)} placeholder="도착지"/><button onClick={find}>경로 찾기</button></div><div className="chips">{layers.map(([x,i,n])=><button key={x} onClick={()=>toggle(x)} className={on.includes(x)?'on':''}><i>{i}</i>{n}</button>)}</div></section>{msg&&<p className="notice">{msg}</p>}<section className="bottom"><div className="goals">{(['산책','운동','시원한 길'] as Goal[]).map(x=><button key={x} className={goal===x?'selected':''} onClick={()=>{setGoal(x);find()}}><b>{x}</b><small>{data[x].why}</small></button>)}</div><div className="compare"><div><small>일반 도보</small><b>{info.normal}</b></div><div className="ai"><small>AI 최적 경로</small><b>{info.d} · {info.t}</b></div><p><b>{g.score}점</b> {g.delta}<br/><span>선택 이유: {g.why}</span></p></div></section><footer>청록색 실선: AI 최적 경로 · 회색 점선: 일반 도보 경로 · 레이어는 경로 주변에 표시됩니다.</footer></main>}
